/**
 * Encode fonts to base64 and generate customVfs.ts
 * This script converts TTF files to base64 strings for embedding in pdfMake
 */

import { readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const fontsDir = join(__dirname, '..', 'public', 'fonts')
const outputFile = join(__dirname, '..', 'src', 'pdf', 'customVfs.ts')

console.log('📦 Encoding fonts to base64...')

try {
  // Read font files
  const robotoPath = join(fontsDir, 'Roboto-Regular.ttf')
  const devanagariPath = join(fontsDir, 'NotoSansDevanagari-Regular.ttf')

  console.log(`Reading ${robotoPath}...`)
  const robotoBuffer = readFileSync(robotoPath)
  const robotoBase64 = robotoBuffer.toString('base64')

  console.log(`Reading ${devanagariPath}...`)
  const devanagariBuffer = readFileSync(devanagariPath)
  const devanagariBase64 = devanagariBuffer.toString('base64')

  // Generate TypeScript file
  const content = `/**
 * Custom VFS for pdfMake
 * Auto-generated by scripts/encode_fonts_to_vfs.mjs
 * DO NOT EDIT MANUALLY
 */

export const customVfs = {
  "Roboto-Regular.ttf": "${robotoBase64}",
  "NotoSansDevanagari-Regular.ttf": "${devanagariBase64}"
}
`

  writeFileSync(outputFile, content, 'utf-8')

  console.log('✅ Successfully generated src/pdf/customVfs.ts')
  console.log(`   Roboto: ${Math.round(robotoBase64.length / 1024)} KB`)
  console.log(`   Devanagari: ${Math.round(devanagariBase64.length / 1024)} KB`)
} catch (error) {
  console.error('❌ Error encoding fonts:', error)
  process.exit(1)
}

